"""update cart

Revision ID: 3ae68c4c6d46
Revises: aec03f68f61a
Create Date: 2025-10-04 19:51:39.995762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ae68c4c6d46'
down_revision: Union[str, Sequence[str], None] = 'aec03f68f61a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cart_items', ['id'])
    op.add_column('carts', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False))
    op.add_column('carts', sa.Column('total_amount', sa.Float(), nullable=False))
    op.create_unique_constraint(None, 'carts', ['id'])
    op.drop_constraint(op.f('carts_product_id_fkey'), 'carts', type_='foreignkey')
    op.drop_column('carts', 'added_at')
    op.drop_column('carts', 'quantity')
    op.drop_column('carts', 'product_id')
    op.create_unique_constraint(None, 'categories', ['id'])
    op.create_unique_constraint(None, 'products', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_constraint(None, 'categories', type_='unique')
    op.add_column('carts', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('carts', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('carts', sa.Column('added_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('carts_product_id_fkey'), 'carts', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'carts', type_='unique')
    op.drop_column('carts', 'total_amount')
    op.drop_column('carts', 'created_at')
    op.drop_constraint(None, 'cart_items', type_='unique')
    # ### end Alembic commands ###
