"""update cart

Revision ID: 824bf93f80a1
Revises: 3ae68c4c6d46
Create Date: 2025-10-04 19:56:35.933062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '824bf93f80a1'
down_revision: Union[str, Sequence[str], None] = '3ae68c4c6d46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('product_id', sa.Integer(), nullable=False))
    op.add_column('carts', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('carts', sa.Column('added_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False))
    op.create_foreign_key(None, 'carts', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_column('carts', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.drop_column('carts', 'added_at')
    op.drop_column('carts', 'quantity')
    op.drop_column('carts', 'product_id')
    # ### end Alembic commands ###
