"""update cart

Revision ID: ee1e4d70aba4
Revises: 824bf93f80a1
Create Date: 2025-10-04 20:08:42.483014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee1e4d70aba4'
down_revision: Union[str, Sequence[str], None] = '824bf93f80a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('carts_product_id_fkey'), 'carts', type_='foreignkey')
    op.drop_column('carts', 'product_id')
    op.drop_column('carts', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('carts', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('carts_product_id_fkey'), 'carts', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
